# Generated by Django 5.0.3 on 2024-03-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_variant',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='product_variant',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
