# Generated by Django 5.0.3 on 2024-03-13 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_product_id_product_variant_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_variant',
            new_name='ProductVariant',
        ),
    ]
